import { join, dirname } from 'node:path'
import { mkdir, writeFile } from 'node:fs/promises'
import { spawn } from 'node:child_process'

import type { CAC } from 'cac'

import {
  consola,
  colors,
  findMonorepoRoot,
  getPackages,
  prettierFormat,
  toPosixPath,
  gitAdd,
} from '@shiyu/node-utils'

async function runCreateVite(targetDir: string, template?: string) {
  // ensure parent exists so pnpm create can create the folder inside it
  await mkdir(dirname(targetDir), { recursive: true })
  const args = template
    ? ['create', 'vite@latest', targetDir, '--', '--template', template]
    : ['create', 'vite@latest', targetDir]
  const cp = spawn('pnpm', args, { stdio: 'inherit' })
  return new Promise<void>((resolve, reject) => {
    cp.on('close', code => {
      code === 0 ? resolve() : reject(new Error(`pnpm create vite failed (${code})`))
    })
    cp.on('error', err => reject(err))
  })
}

async function createPackageScaffold(options: {
  root: string
  name: string
  kind: 'package' | 'app'
  isPrivate?: boolean
  template?: string | undefined
}) {
  const { root, name, kind, isPrivate = true, template } = options
  const base = kind === 'app' ? 'apps' : 'packages'
  const dir = join(root, base, name)

  const { packages } = await getPackages()
  if (packages.some(p => p.packageJson.name === `@shiyu/${name}` || p.dir === dir)) {
    throw new Error(`Package or folder already exists: ${name}`)
  }

  if (kind === 'app') {
    // delegate to pnpm create vite and forward STDIO
    consola.info(colors.cyan('Running pnpm create vite...'))
    await runCreateVite(dir, template)
    // try format package.json if possible
    try {
      await prettierFormat(join(dir, 'package.json'))
    } catch {
      /* ignore */
    }
    return dir
  }

  // package scaffold
  await mkdir(join(dir, 'src'), { recursive: true })

  const pkg = {
    name: `@shiyu/${name}`,
    version: '0.0.0',
    private: isPrivate,
    type: 'module',
    main: 'dist/index.mjs',
    module: 'dist/index.mjs',
    exports: {
      '.': {
        types: 'dist/index.d.ts',
        import: 'dist/index.mjs',
      },
    },
    scripts: {
      build: 'tsc -p tsconfig.json',
      dev: 'vite',
    },
  }

  const tsconfig = {
    extends: '@shiyu/tsconfig/web.json',
    include: ['src'],
  }

  const indexTs = `export const hello = () => 'hello @shiyu/${name}'\n`

  await writeFile(join(dir, 'package.json'), JSON.stringify(pkg, null, 2), 'utf8')
  await writeFile(join(dir, 'tsconfig.json'), JSON.stringify(tsconfig, null, 2), 'utf8')
  await writeFile(join(dir, 'src', 'index.ts'), indexTs, 'utf8')
  await writeFile(join(dir, 'README.md'), `# @shiyu/${name}\n\nGenerated by vsh addrepo\n`, 'utf8')

  // 尝试格式化（若 prettier 可用）
  try {
    await prettierFormat(join(dir, 'package.json'))
    await prettierFormat(join(dir, 'tsconfig.json'))
    await prettierFormat(join(dir, 'src', 'index.ts'))
    await prettierFormat(join(dir, 'README.md'))
  } catch {
    /* ignore */
  }

  return dir
}

/**
 * 注册 addrepo 命令
 * Usage:
 *   pnpm vsh addrepo <name> --kind package|app [--git-add] [--template react|vue|vanilla]
 */
export function defineAddrepoCommand(cac: CAC) {
  cac
    .command('addrepo <name>')
    .alias('scaffold')
    .option('--kind <kind>', 'Kind: package or app', { default: 'package' })
    .option('--git-add', 'Automatically git add created files', { default: false })
    .option('--template <tpl>', 'vite template when kind=app (e.g. react, vue, vanilla)', {
      default: undefined,
    })
    .usage('Create a minimal package/app in the monorepo')
    .action(
      async (
        name: string,
        opts: { kind?: string; gitAdd?: boolean; template?: string | undefined }
      ) => {
        try {
          const root = findMonorepoRoot()
          if (!name) {
            consola.error(colors.red('Name is required'))
            process.exit(1)
          }
          const dir = await createPackageScaffold({
            root,
            name,
            kind: opts.kind === 'app' ? 'app' : 'package',
            isPrivate: true,
            template: opts.template,
          })
          consola.success(colors.green(`Created: ${toPosixPath(dir)}`))

          if (opts.gitAdd) {
            try {
              await gitAdd(dir, root)
              consola.log(colors.dim('Files added to git index'))
            } catch {
              consola.warn(colors.yellow('git add failed (git may be unavailable)'))
            }
          }
        } catch (err) {
          consola.error(colors.red((err as Error).message))
          process.exit(1)
        }
      }
    )
}
